export default function TermsPage() {
    return (
      <main className="min-h-screen px-6 py-12 max-w-2xl mx-auto" style={{ color: "#ededed" }}>
        <h1 className="text-3xl font-bold mb-2" style={{ color: "#C9A84C" }}>Terms of Service</h1>
        <p className="text-xs mb-10" style={{ color: "#555" }}>Last updated: May 11, 2026</p>
  
        <section className="space-y-8 text-sm leading-relaxed" style={{ color: "#aaa" }}>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>1. About Scanify</h2>
            <p>Scanify is an AI-powered item valuation service that allows users to scan physical items and receive estimated values, price history, and related information. Scanify is operated from Sweden and is subject to Swedish law.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>2. Acceptance of Terms</h2>
            <p>By using Scanify, you agree to these Terms of Service. If you do not agree, please do not use the service. We may update these terms from time to time and will notify users of significant changes.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>3. Use of the Service</h2>
            <p>Scanify is intended for personal, non-commercial use. You agree not to misuse the service, attempt to reverse-engineer it, or use it for any unlawful purpose. We reserve the right to suspend accounts that violate these terms.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>4. AI-Generated Valuations</h2>
            <p>All valuations provided by Scanify are generated by artificial intelligence and are estimates only. They should not be relied upon for financial, insurance, legal, or investment decisions. Scanify makes no guarantees about the accuracy of any valuation.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>5. Subscriptions and Payments</h2>
            <p>Scanify offers free and paid subscription plans. Paid plans are billed monthly through Stripe. You may cancel your subscription at any time. Refunds are handled on a case-by-case basis — contact us if you have a billing issue.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>6. User Content</h2>
            <p>When you upload images to Scanify, you grant us a limited licence to process and store those images for the purpose of providing the service. We do not sell your images to third parties.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>7. Limitation of Liability</h2>
            <p>To the fullest extent permitted by Swedish law, Scanify is not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
          </div>
  
          <div>
            <h2 className="text-base font-semibold mb-2" style={{ color: "#ededed" }}>8. Contact</h2>
            <p>For any questions about these terms, contact us at <a href="mailto:bezjak3797jacked3707@gmail.com" style={{ color: "#C9A84C" }}>bezjak3797jacked3707@gmail.com</a>.</p>
          </div>
  
        </section>
      </main>
    );
  }