export default function TermsPage() {
  return (
    <main className="min-h-screen pb-24 px-6 py-10" style={{ background: "var(--color-black)", color: "#ededed" }}>
      <div className="max-w-md mx-auto space-y-6">
        <div className="text-center space-y-1">
          <p className="text-xs uppercase tracking-widest" style={{ color: "var(--color-gold)" }}>Legal</p>
          <h1 className="text-3xl" style={{ fontFamily: "var(--font-heading)", fontWeight: 500 }}>Terms of Service</h1>
          <p className="text-xs" style={{ color: "#555" }}>Last updated: August 2026</p>
        </div>

        {[
          {
            title: "1. Acceptance of Terms",
            content: "By using Scanify you agree to these terms. If you do not agree, do not use the service."
          },
          {
            title: "2. Description of Service",
            content: "Scanify provides AI-powered object identification and valuation. Results are estimates generated by artificial intelligence and should not be used as the sole basis for financial, insurance, or resale decisions."
          },
          {
            title: "3. Eligibility",
            content: "You must be at least 13 years old to use Scanify. If you are under the age of majority in your country, you may only use Scanify with the involvement of a parent or legal guardian."
          },
          {
            title: "4. User Accounts",
            content: "You must sign in with a valid Google or Apple account to use Scanify. You are responsible for all activity under your account and for keeping your account credentials secure."
          },
          {
            title: "5. Subscriptions and Payments",
            content: "Pro and Business plans are billed monthly through Stripe on our website. You can manage or cancel your subscription at any time through your profile page or at scanify.world. Cancellations take effect at the end of the current billing period. Scanify's mobile apps do not currently process payments directly; subscription management is handled via our website."
          },
          {
            title: "6. Free Plan Limits",
            content: "Free accounts receive 3 scans per month. Scan counts reset at the start of each calendar month."
          },
          {
            title: "7. Accuracy Disclaimer",
            content: "Scanify uses AI to estimate values and identify items. We do not guarantee the accuracy, completeness, or currentness of any valuation or identification. Always verify with a qualified professional before making financial decisions based on a Scanify result."
          },
          {
            title: "8. Prohibited Use",
            content: "You may not submit false, misleading, manipulated, or unlawfully obtained images to Scanify, including to the public leaderboard. We reserve the right to remove any content, revoke leaderboard eligibility, and suspend or terminate accounts that violate this policy."
          },
          {
            title: "9. Account Deletion",
            content: "You may permanently delete your account and associated data at any time from your profile page. This action is irreversible and removes your scan history, images, and account information from our systems."
          },
          {
            title: "10. Intellectual Property",
            content: "All content, design, and code of Scanify is owned by Scanify. You may not copy, reproduce, or distribute any part of the service without permission."
          },
          {
            title: "11. Changes to Terms",
            content: "We may update these terms at any time. Continued use of Scanify after changes means you accept the new terms."
          },
          {
            title: "12. Governing Law",
            content: "These terms are governed by the laws of Sweden, without regard to conflict of law principles."
          },
          {
            title: "13. Contact",
            content: "For questions about these terms please contact us through the contact form on our homepage."
          },
        ].map((section) => (
          <div key={section.title} className="rounded-2xl p-5 space-y-2" style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)" }}>
            <h2 className="text-sm font-semibold" style={{ color: "var(--color-gold)" }}>{section.title}</h2>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>{section.content}</p>
          </div>
        ))}
      </div>
    </main>
  );
}

export {};